# Generated by Django 4.0.4 on 2022-05-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='desc',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
