# Generated by Django 4.0.4 on 2022-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_profesional_profregion_profesional_workplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
