# Generated by Django 4.0.4 on 2022-06-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_delete_paciente_alter_profesional_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
